### ISSUE TITLE
NAIP 2018-2019

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/incoming-data#1]
Please reassign issues when your work is complete.

**Data**
- [x] Enter dataset on StratMap Incoming data xlsx sheet @gmullins 
- [x] Route Data Shipment (copy data to TNRIS Projects share) @LaurenKirk 
- [x] Data Processing (renaming file, data organization) @mitchellryant
- [x] Creation of derivative products [compressed images] @LaurenKirk @csidenblad 
- [x] Quality Assurance @LaurenKirk @csidenblad 
- [x] Send inventory list/shp to NRCS @gmullins 

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @gmullins 
- [x] Create Images, place on Website Dir @gmullins  
- [ ] Crop & Upload Images @christoball 
- [x] Upload supplemental info (breaklines, reports, index) @gmullins<br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_ 
- [x] Review Description @pwblanton
- [x] Add resources @mitchellryant

**Download\Prod**
- [x]  Move data to production shares @mitchellryant
- [x] Make collection public @mitchellryant
- [ ] WMS Link @mitchellryant 
- [x]  Inform TNRIS staff of data availability @mitchellryant 

**News Article**
* If you choose to write an article about the data release
* Create a new issue in the [tnris.org repo](https://github.com/TNRIS/tnris.org). 
* Please assign to yourself and @christoball.
* Use the Data Release and New Article labels.
* Provide all content as a comment in the issue.

**Comment by mitchellryant** [comment]
@LaurenKirk @csidenblad please create an index for both tif and Jp2 and check to see if all images were converted.

**Comment by mitchellryant** [comment]
@gmullins have you heard anything on the metadata?

**Comment by gmullins** [comment]
@mitchellryant Not yet. Putting out another feeler.

**Comment by csidenblad** [comment]
@mitchellryant All tiles have been converted and index created. Index can be found in R:\StratMap\Orthoimagery\naip-2019-nc-cir-60cm named after collection.

**Comment by gmullins** [comment]
@mitchellryant Ready for the rest of your tasks.
@pwblanton Ready for your review of the description in the console.
Thanks!

**Comment by gmullins** [comment]
@christoball I inadvertently uploaded images already in the console. You may want to check them out size-wise. Originals are here: M:\SM\Imagery\NAIP\NAIP2018_19\Web_announce\Graphics

**Comment by christoball** [comment]
@gmullins @gmullins I've deleted them all, they were all 15MB at 300dpi. Please give me the heads up when you want images added, I'll crop and upload them.

**Comment by gmullins** [comment]
@christoball These are the ones I'd like on DataHub. Starred is thumbnail.
![image](https://user-images.githubusercontent.com/4921113/66068727-c09a7c80-e513-11e9-8682-d77d4a34931a.png)

**Comment by mitchellryant** [comment]
@gmullins @christoball can we get the images cropped and loaded? @gmullins wants to make an announcement that the data is ready at a meeting Tuesday.

**Comment by christoball** [comment]
@mitchellryant yes, making this a top priority to upload images and have the story draft by this afternoon.

**Comment by christoball** [comment]
@mitchellryant @gmullins the images have been processed and uploaded
