### ISSUE TITLE
USACE 2018 Buffalo Bayou lidar

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/incoming-data#2]
Please reassign issues when your work is complete.

**Data**
- [ ] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization]  @ThorTheDestroyer
- [x] Creation of derivative products [hypso and metadata] @ThorTheDestroyer
- [ ] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @ThorTheDestroyer 
- [x] Create Images, place on Website Dir @ThorTheDestroyer 
- [x] Crop & Upload Images @christoball 
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer
- [x] Review Description @pwblanton
- [x] Add resources  @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant 
- [x]  Inform TNRIS staff of data availability @mitchellryant

**Comment by mitchellryant** [comment]
@christoball images are here - vault/Website/datacatalog/images/usace18-50cm-buffalobayou

**Comment by christoball** [comment]
@mitchellryant I've uploaded the cropped and resized images to the admin console

**Comment by mitchellryant** [comment]
@ThorTheDestroyer please add the description.

**Comment by mitchellryant** [comment]
@christoball i place a 3rd image in the dir (coverage.jpg). can you crop and upload? it is a coverage map for the collection. This collection is unlike any others, flown in swaths and covering just Buffalo Bayou in Harris County. The third image will help users understand what is covers.

**Comment by christoball** [comment]
@mitchellryant image is now uploaded

**Comment by mitchellryant** [comment]
@christoball thank you

**Comment by mitchellryant** [comment]
@ThorTheDestroyer added EPSG code it domain table, selected EPSG code in console, and made collection public.

**Comment by pwblanton** [comment]
Made a couple of typographical corrections.
