### ISSUE TITLE
USGS South Texas

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/incoming-data#3]
Please reassign issues when your work is complete.

**Data**
- [ ] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization, data conversion]  @mitchellryant 
- [x] Creation of derivative products [hypso and metadata] @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @ThorTheDestroyer 
- [x] Create Images, place on Website Dir @ThorTheDestroyer 
- [x] Crop & Upload Images @christoball 
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer<br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_
- [x] Review Description @pwblanton
- [x] Add resources  @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant 
- [x]  Inform TNRIS staff of data availability @mitchellryant 

**News Article**
* If you choose to write an article about the data release
* Create a new issue in the [tnris.org repo](https://github.com/TNRIS/tnris.org). 
* Please assign to yourself and @christoball.
* Use the Data Release and New Article labels.
* Provide all content as a comment in the issue.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer 
**Block 8** 
```
las - 2,943 files
laz - 1,693 files
```

**Collection**
```
dem - 26,260 files
laz - 23,261 files
```

is there metadata for block 8?

**Comment by ThorTheDestroyer** [comment]
I'm looking into it, there are still a few things I need to sort out. I believe the DEMs are solid.

**Comment by ThorTheDestroyer** [comment]
@christoball images are in directory   \Website\datacatalog\images\usgs18-south_texas

**Comment by christoball** [comment]
@ThorTheDestroyer @mitchellryant I've processed the images and uploaded to tnris API.

**Comment by ThorTheDestroyer** [comment]
looks good

**Comment by mitchellryant** [comment]
@ThorTheDestroyer hypso metadata?

**Comment by ThorTheDestroyer** [comment]
[usgs18-metadata-contours.txt](https://github.com/TNRIS/incoming-data/files/3819954/usgs18-metadata-contours.txt)
[usgs18-metadata-contours.pdf](https://github.com/TNRIS/incoming-data/files/3819955/usgs18-metadata-contours.pdf)

**Comment by mitchellryant** [comment]
@ThorTheDestroyer collection is now public.
