### ISSUE TITLE
Address Points

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/incoming-data#4]
Please reassign issues when your work is complete.

**Data**
- [ ] Add data to measures spreadsheet @ilyannakadich 
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ilyannakadich
- [x] Data Processing [renaming file, data organization]  @ilyannakadich
```
naming convention for shape and fgdb.
stratmap19-addresspoints_fipscode_countyname_date.extension
stratmap19-addresspoints_48001_anderson_201904.shp
stratmap19-addresspoints_48001_anderson_201904.gdb
```
- [x] Quality Assurance @ilyannakadich

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @ilyannakadich 
- [x] Create Images, place on Website Dir @ilyannakadich 
- [x] Upload supplemental info (breaklines, reports, index) @ilyannakadich 
`If zip file is too large (more than 75MB) please let` @mitchellryant `know and the file can be loaded in another way.`
- [x] Crop & Upload Images @christoball 
- [x] Review Description @gmullins 
- [x] Add resources  @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant 
- [x] Inform TNRIS staff of data availability @mitchellryant

**News Article**
* If you choose to write an article about the data release
* Create a new issue in the [tnris.org repo](https://github.com/TNRIS/tnris.org). 
* Please assign to yourself and @christoball.
* Use the Data Release and New Article labels.
* Provide all content as a comment in the issue.

**Comment by ilyannakadich** [comment]
[TNRIS Address Point Schema.pdf](https://github.com/TNRIS/incoming-data/files/3778585/TNRIS.Address.Point.Schema.pdf)
 Please add the schema to the supplemental info folder

**Comment by mitchellryant** [comment]
@ilyannakadich the file is only 512KB, zipped it will load without issues in the api admin console.

**Comment by ilyannakadich** [comment]
@mitchellryant  OK, i saved it there.

**Comment by mitchellryant** [comment]
@ilyannakadich Can you correct 1-3? I can bulk correct 4-5? 

1. the shape file and fgdb feature class for **Bandera** is missing a `d`
2.  the shape file and fgdb feature class for **Caldwell**  the name is `countyname_FIPS` it should be `FIPS_countyname`.
3.  the shape file for **Hardin** has the `_conversion` in the file name
4. the file geodatabase name should be `stratmap19-addresspoints_fipscode_countyname_date.gdb`
5. the shape file names should be `stratmap19-addresspoints_fipscode_countyname_date.gdb`

**Comment by ilyannakadich** [comment]
@mitchellryant Got it done.  Thanks!

**Comment by gmullins** [comment]
@ilyannakadich Description looks good. You could say this is an update to the previous 2017 points that are now archived at TNRIS. Also, I suggest adding in info such as this which I grabbed off the land parcels article and anything else pertaining to the data that you think users need to know:

Each land parcel dataset on DataHub consists of a zip file including:
File geodatabase
Shapefile
Conversion file (field mappings from the source to the common schema)
Metadata

**Comment by ilyannakadich** [comment]
@mitchellryant  I made the updates per Gayla's recommendation.

**Comment by mitchellryant** [comment]
@ilyannakadich @gmullins collection is public.
