### ISSUE TITLE
USGS 2018 Panhandle

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/incoming-data#40]
Please reassign issues when your work is complete.

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization, data conversion]  @mitchellryant 
- [x] Creation of derivative products [hypso and metadata] @csidenblad @LaurenKirk @ThorTheDestroyer 
- [ ] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @csidenblad @LaurenKirk @ThorTheDestroyer  
- [ ] Format Description to ensure customer readability and understanding. @ThorTheDestroyer
- [x] Create Images, place on Website Dir @csidenblad @LaurenKirk @ThorTheDestroyer  
- [x] Crop & Upload Images @christoball 
- [x] Upload supplemental info (breaklines, reports, index) @csidenblad @LaurenKirk @ThorTheDestroyer  <br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_
- [x] Review Description and Formatting @pwblanton
- [x] Add resources  @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant 
- [x] Inform TNRIS staff of data availability @mitchellryant

**Twitter**
*News Articles are dead, please discuss with Twitter team about Tweeting completed collection link.

**Comment by mitchellryant** [comment]
@csidenblad @LaurenKirk @ThorTheDestroyer  the data has been zipped and is currently loading to s3. you guys fight amongst yourselves to fill out the console.

**Comment by mitchellryant** [comment]
@csidenblad @LaurenKirk @ThorTheDestroyer resources for LPC and DEM files have been added. All that is left is everything.

**Comment by ThorTheDestroyer** [comment]
@mitchellryant I wrote the description last week. I'll try to finish out the console soon.

**Comment by ThorTheDestroyer** [comment]
@christoball images are loaded to   \Website\datacatalog\images\usgs18_panhandle

**Comment by christoball** [comment]
@mitchellryant @ThorTheDestroyer the images have been edited and uploaded

**Comment by ThorTheDestroyer** [comment]
@christoball Thanks chris, added captions to the images.

**Comment by ThorTheDestroyer** [comment]
@csidenblad @LaurenKirk  did the contours finish? or did you cancel the operation per my initial instructions when I discovered the truth?

**Comment by csidenblad** [comment]
@ThorTheDestroyer @LaurenKirk Contours have not yet been created. We did stop the process and were told to wait until we got an updated license for GlobalMapper. Once new software is installed, we will restart the process.

**Comment by mitchellryant** [comment]
collection has been made public, while hypso lines are being generated.

**Comment by csidenblad** [comment]
@mitchellryant @ThorTheDestroyer @LaurenKirk contours are created and in folder on r: 
Can we please also add the index to i: ? Thank you.

**Comment by mitchellryant** [comment]
@csidenblad @LaurenKirk I will have to come into the office to move the hypos files to I:\ and start the zipping. Not sure the connection through tserv will stay active long enough to complete the process.

**Comment by mitchellryant** [comment]
@csidenblad @LaurenKirk @ThorTheDestroyer hypso has been moved to lidar prod. I cannot start the zipping from the house. i think the selector is was already updated.

**Comment by mitchellryant** [comment]
@csidenblad @LaurenKirk started zipping hypso could be in the cloud by mid day tomorrow.
