### ISSUE TITLE
USGS 2018 Texas West Central

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/incoming-data#43]
Please reassign issues when your work is complete.

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization, data conversion]  @mitchellryant 
- [ ] Creation of derivative products [hypso and metadata] @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @ThorTheDestroyer 
- [ ] Format Description to ensure customer readability and understanding. @ThorTheDestroyer
- [x] Create Images, place on Website Dir @ThorTheDestroyer 
- [x] Crop & Upload Images @christoball 
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer<br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_
- [x] Review Description and Formatting @pwblanton
- [x] Add resources  @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant 
- [x] Inform TNRIS staff of data availability @mitchellryant

**Twitter**
*News Articles are dead, please discuss with Twitter team about Tweeting completed collection link.

**Comment by ThorTheDestroyer** [comment]
@mitchellryant even after removing photos, the supplemental report is still too large, please upload, zip file is located at StratMap\lidar\usgs18-70cm-Texaswestcentral\qaqc

**Comment by mitchellryant** [comment]
@ThorTheDestroyer supplemental report has been uploaded.

**Comment by ThorTheDestroyer** [comment]
@christoball images have been loaded to the directory below.  Let me know if you would like any changes made to them. 

\Website\datacatalog\images\usgs18-westcentraltexas

**Comment by christoball** [comment]
@ThorTheDestroyer I've edited and added to the data catalog entry

**Comment by christoball** [comment]
@ThorTheDestroyer also, props on this artsy rendering. You're the Monet of Lidar!

![usgs18-westcentral_redriver-lakebridgeport-web](https://user-images.githubusercontent.com/1877550/72110218-40976600-32fd-11ea-985c-9e6e2d906ff1.jpg)
