### ISSUE TITLE
Split Collection

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/incoming-data#44]
can you prep this images for loading into DataHub? `Website\data.tnris.org\2015-stratmap-nga`

I had to split the collection into 4 collection to add the Web Services.

**Comment by mitchellryant** [comment]
@christoball could i get an update on this.

**Comment by christoball** [comment]
@mitchellryant Sorry, lost track of this. I've added the images in the same folder with _web on the filename

**Comment by mitchellryant** [comment]
@christoball no worries
