### ISSUE TITLE
USGS 2018 Matagorda Bay Lidar

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/incoming-data#45]
Please reassign issues when your work is complete.

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization, data conversion]  @mitchellryant 
- [x] Creation of derivative products [hypso and metadata] @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @ThorTheDestroyer 
- [x] Create Images, place on Website Dir @ThorTheDestroyer 
- [x] Crop & Upload Images @christoball 
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer<br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_
- [x] Review Description @pwblanton
- [x] Add resources  @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant 
- [x] Inform TNRIS staff of data availability @mitchellryant

**News Article**
* If you choose to write an article about the data release
* Create a new issue in the [tnris.org repo](https://github.com/TNRIS/tnris.org). 
* Please assign to yourself and @christoball.
* Use the Data Release and New Article labels.
* Provide all content as a comment in the issue.

**Comment by ThorTheDestroyer** [comment]
Data received  on 02-03-20

**Comment by ThorTheDestroyer** [comment]
@christoball  collection images are located below. 

Website\datacatalog\images\usgs18-matagordabay

**Comment by mitchellryant** [comment]
@ThorTheDestroyer @christoball all resources (**LPC, DEM, Hypso**) have been added. Everything else is everything else and up to you.

**Comment by christoball** [comment]
@ThorTheDestroyer @mitchellryant Images have been edited and added to api console.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer  all eyes on you

**Comment by ThorTheDestroyer** [comment]
@pwblanton  Please review the description. Thank you!

This USGS lidar project covers 705 square miles over portions of western Matagorda County, Texas. The acquisition was conducted from January 24, 2019, through January 29, 2019. Fugro was tasked with planning, acquiring, processing, and producing high resolution lidar data and derivative products. Lidar data, and derivative products were produced in compliance with the task order and are based on the “U.S. Geological Survey National Geospatial Program Lidar Base Specification Version 1.2”.

Data for this project was acquired to support the 3DEP mission and complete recent coastal lidar coverage for Texas. 

Further details regarding this acquisition can be found by downloading the USGS 2019 Matagorda Bay Project Reports.


Points are classified based on the following classifications. 

Class 1: Unclassified
Class 2: Ground
Class 3: Low vegetation
Class 4: Medium vegetation
Class 5: Tall vegetation
Class 6: Buildings
Class 7: Low Noise
Class 9: Water
Class 10: Ignored Ground
Class 14: Culverts
Class 17: Bridges
Class 18: High Noise

**Comment by pwblanton** [comment]
Only made one change; deleted one comma. 

This USGS lidar project covers 705 square miles over portions of western Matagorda County, Texas. The acquisition was conducted from January 24, 2019, through January 29, 2019. Fugro was tasked with planning, acquiring, processing, and producing high resolution lidar data and derivative products. Lidar data and derivative products were produced in compliance with the task order and are based on the “U.S. Geological Survey National Geospatial Program Lidar Base Specification Version 1.2”.

Data for this project was acquired to support the 3DEP mission and complete recent coastal lidar coverage for Texas.

Further details regarding this acquisition can be found by downloading the USGS 2019 Matagorda Bay Project Reports.

Points are classified based on the following classifications.

Class 1: Unclassified
Class 2: Ground
Class 3: Low vegetation
Class 4: Medium vegetation
Class 5: Tall vegetation
Class 6: Buildings
Class 7: Low Noise
Class 9: Water
Class 10: Ignored Ground
Class 14: Culverts
Class 17: Bridges
Class 18: High Noise

**Comment by mitchellryant** [comment]
@ThorTheDestroyer  Missing Source ID, Partners, and License.

**Comment by ThorTheDestroyer** [comment]
@mitchellryant  done.  There were no other partners so I just put USGS.
