### ISSUE TITLE
TNRIS Resources Guide

### ISSUE THREAD

**Issue by KCMack** [TNRIS/incoming-data#46]
Please add the Resources List to the website as we discussed
[Texas Natural Resources Information System Resources.docx](https://github.com/TNRIS/incoming-data/files/4231484/Texas.Natural.Resources.Information.System.Resources.docx)

@christoball

**Comment by christoball** [comment]
@KCMack this would go in the tnris.org repository. I've created a new issue there for this. 
https://github.com/TNRIS/tnris.org/issues/168
