### ISSUE TITLE
Balmorhea & Davis Mountain State Park Lidar and Imagery

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/incoming-data#48]
Please reassign issues when your work is complete.

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization, data conversion]  @mitchellryant 
- [x] Creation of derivative products [hypso and metadata] @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @ThorTheDestroyer 
- [x] Crop & Upload Images @mitchellryant 
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer<br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_
- [x] Review Description and Formatting @pwblanton https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant 

**Twitter**
*News Articles are dead, please discuss with Twitter team about Tweeting completed collection link.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer i think you will need to export the hypso lines out.

![Davis](https://user-images.githubusercontent.com/8459928/85028655-fa162500-b140-11ea-91f0-28a905faccf5.PNG)

**Comment by ThorTheDestroyer** [comment]
Sorry, i meant to note the other day that i did that. there is a 1ft contour in the hypso folder for the entire project.  Would you prefer them split or are they okay as 1 file?

**Comment by ThorTheDestroyer** [comment]
oh dang, nevermind. now i see that i messed up the export.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer is this the coverage area for the lidar and imagery?
![coverage](https://user-images.githubusercontent.com/8459928/85414108-4bebf000-b531-11ea-8f3c-996009ba3012.PNG)

**Comment by ThorTheDestroyer** [comment]
yes that looks correct. I'm planning on going back into the office tomorrow and I'll verify.
