### ISSUE TITLE
StratMap 2020 CapArea & McLennan Imagery

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/incoming-data#49]
Please reassign issues when your work is complete.

**Data**
- [x] Enter dataset on StratMap Incoming data xlsx sheet @ThorTheDestroyer
- [x] Route Data Shipment (copy data to TNRIS Projects share) @ThorTheDestroyer 
~~- [ ] Data Processing (renaming file, data organization) @mitchellryant~~
~~- [ ] Creation of derivative products [compressed images] @ThorTheDestroyer~~
- [x] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @ThorTheDestroyer 
- [x] Crop & Upload Images @ThorTheDestroyer 
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer<br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_
- [x] Review Description @pwblanton
- [x] Add resources @mitchellryant

**Download\Prod**
- [x]  Move data to production shares @mitchellryant
- [x] Make collection public @mitchellryant
~~- [ ] WMS Link @mitchellryant~~ 
~~- [ ] Inform TNRIS staff of data availability @mitchellryant~~

**Twitter**
*News Articles are dead, please discuss with Twitter team about Tweeting completed collection link.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer i removed the lidar template and used the imagery template.

**Comment by gmullins** [comment]
@mitchellryant and @ThorTheDestroyer
These assignments look good w/o @csidenblad or @LaurenKirk on this one. 
I don't think we're going to need this one: Creation of derivative products [compressed images] 
Thank you both!! Let me know if I can help or questions.

**Comment by mitchellryant** [comment]
3 different tiles, resolution, and dates. one tile.

![ohboy](https://user-images.githubusercontent.com/8459928/88803649-676e9a00-d172-11ea-9cf3-b1c73c576ca5.PNG)

**Comment by mitchellryant** [comment]
![incoming_data](https://user-images.githubusercontent.com/8459928/88805609-fd0b2900-d174-11ea-90c3-d87e3cb24785.jpg)

**Comment by mitchellryant** [comment]
![ohboy](https://user-images.githubusercontent.com/8459928/88805653-08f6eb00-d175-11ea-8871-228d900b5641.PNG)

**Comment by mitchellryant** [comment]
@ThorTheDestroyer so there are tiles for both 6in and 12in?
![dup](https://user-images.githubusercontent.com/8459928/88811424-23809280-d17c-11ea-9d14-4018ada35bec.PNG)

**Comment by ThorTheDestroyer** [comment]
Yes, from my understanding.  The capcog area has complete 12-inch coverage, with select areas additionally in 6 inch and 3 inch(west lake hills only).

**Comment by mitchellryant** [comment]
cool. it does not really affect my process. might think about putting that in the collection description.

**Comment by ThorTheDestroyer** [comment]
@pwblanton Please review the console description.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer you can re-assign issues in the repo.

**Comment by pwblanton** [comment]
I already reviewed it; no changes were needed.
