### ISSUE TITLE
USGS 2019 West Texas Lidar

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/incoming-data#50]
Please reassign issues when your work is complete.

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization, data conversion]  @mitchellryant 
- [ ] Creation of derivative products [hypso and metadata] @ThorTheDestroyer
- [ ] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @ThorTheDestroyer 
- [x] Crop & Upload Images @ThorTheDestroyer  
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer<br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_
- [x] Review Description and Formatting @pwblanton
- [x] Add resources  @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant 

**Twitter**
*News Articles are dead, please discuss with Twitter team about Tweeting completed collection link.

**Comment by mitchellryant** [comment]
Converted +34k of +38k.  created batch to convert remaining.


**Example of Error**
R:\usgs19-west-texas>c:\LAStools\bin\laszip -i  R:\usgs19-west-texas\las\usgs19-70cm_14RLS495905.las -odir R:\usgs19-west-texas\laz\
ERROR: 'end-of-file' after 2158318 of 9073777 points for 'R:\usgs19-west-texas\las\usgs19-70cm_14RLS495905.las'
WARNING: written 2158318 points but expected 9073777 points
The system cannot open the device or file specified.

**Comment by ThorTheDestroyer** [comment]
@pwblanton console description is completed, please review at your convenience.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer can you add the metadata to the supplemental downloads? It was not added to the resource zips.
Can you upload the tile index?
