### ISSUE TITLE
NAIP 2020

### ISSUE THREAD

**Issue by A-M-Pearce** [TNRIS/incoming-data#55]
The owner of this issue (person who opened it) is responsible for ensuring each task is completed. 
**Please reassign issues** when work is complete. The owner of this issue is responsible for checking in with workmates on progress of each task.

**Data CCMs**
- [x] Enter dataset on StratMap Incoming data xlsx sheet @A-M-Pearce
- [x] Route Data Shipment (copy data to TNRIS Projects share) @mitchellryant
- [x] Data Processing (renaming file, data organization) @mitchellryant
- [x] Quality Assurance @A-M-Pearce

**Data DOQQs**
- [x] Route Data Shipment (copy data to TNRIS Projects share) @A-M-Pearce 
- [x] Data Processing (downloading, renaming file, data organization) @mitchellryant @jwhaney 
- [ ] Quality Assurance @A-M-Pearce

**API\data.tnris.org**
- [x] Create collection @mitchellryant 
- [x] Complete console collection form including metadata and description @A-M-Pearce
- [x] Crop & Upload Images @A-M-Pearce
- ~~[ ] Upload supplemental info (reports, index)~~ @A-M-Pearce<br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_
- [x] Review Description and Formatting @pwblanton https://api.tnris.org/admin/lcd/collection/
- [ ] Add resources @mitchellryant
- - [x] CCMs
- - [ ] DOQQs

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- - [x] CCMs
- - [x] DOQQs
- [x] Make collection public @mitchellryant
- [x] Inform TNRIS staff of data availability @mitchellryant

**Twitter**
- [x] Draft Tweet content, link, and image in Comment @A-M-Pearce
- [x] Post Tweet @geochik

**Comment by mitchellryant** [comment]
collection card - [Texas NAIP Imagery](https://api.tnris.org/admin/lcd/collection/aa5183ca-a1bd-4b5f-9b63-4ba48d01b83d/)

network - naip-2020-nc-cir-60cm\compressed-county-mosaic\

**Comment by mitchellryant** [comment]
@A-M-Pearce @gmullins 

something will need to be figured out with the doqqs. at this time we do not have access to the erdas license in aws, so converting from geotiff to jpg2000 is an unknown. 
also clicking (3 times) every download for 17k+ files in not really how anyone want to spend their day(s).

**Comment by gmullins** [comment]
@mitchellryant Could we use ArcGIS Pro to convert the doqqs from geotiff to jpg2000 in aws?

**Comment by mitchellryant** [comment]
it is a possibility.!? ¯\_(ツ)_/¯. it may not be able to handle the stress. in erdas we were able to load all into the conversion process, and let it run for 4-7 days.

**Comment by ThorTheDestroyer** [comment]
Does the newest version of GM have the same issues with the 4band imagery  as the old versions?  I'm still waiting on IT to install it on my machine, so I'm unable to verify. Might be worth a check.

**Comment by mitchellryant** [comment]
@gmullins @ThorTheDestroyer @A-M-Pearce 

Using GM is a possibility. 

Also just an idea don't compress them. Free the GeoTiff. [Give the people what they want!!!!](https://www.youtube.com/watch?v=mYS6ifV9IN0)

![Ojays](https://user-images.githubusercontent.com/8459928/107533328-72c06a80-6b84-11eb-8e93-afaf842f7148.PNG)

**Comment by gmullins** [comment]
@mitchellryant thank you for the funk :) Is that a possibility? I assumed they were too big to make downloadable from our site. Maybe not no mo?

**Comment by mitchellryant** [comment]
[nothing is too large for the site](https://www.youtube.com/watch?v=gjKFCYzqq-A), maybe to large for the user.  some of the ccms are +5gb per band combo. almost everything is possible, but it would determine on original size of geotiff. there will not be much compression on zipping a geotiff.

**Comment by gmullins** [comment]
I haven't looked into finding/getting the DOQQs yet. BUT I think this is the service link: https://gis.apfo.usda.gov/arcgis/rest/services
@mitchellryant Is this what you want to use to make available on the DataHub?
@A-M-Pearce Can you please check it out and see if the 2020 data have been added? I think they just show the most recent year per state. Here's an [old document](https://www.fsa.usda.gov/Assets/USDA-FSA-Public/usdafiles/APFO/imagery-programs/pdfs/naip/2017_apfo_webservice_10.pdf) on it.
Thanks!

**Comment by A-M-Pearce** [comment]
It looks like they've changed up that service link. Instead of individual state datasets, now everything is mosaicked in one layer, USDA_CONUS_PRIME. It does look like there are 2020 DOQQs within this mosaic in its attribute table (and a couple of 2014 DOQQs along the coastal TX boundary also). There's also a section for image dates, though that's only 2011-2017. 

![image](https://user-images.githubusercontent.com/75264751/109727008-3e374180-7b79-11eb-8fa3-d14c94888aeb.png)

**Comment by gmullins** [comment]
Thanks Aaron! I had a thought on timing. Could we target **April 26th** to have the CCMs available for download from the DataHub? April 27th is the Community Meeting where it will be great to announce this.

**Comment by A-M-Pearce** [comment]
Yes Gayla, it should not be a problem having the CCMs available for download on the DataHub by April 26th!

**Comment by mitchellryant** [comment]
@gmullins we can have these in data.tnris.org this week. I understand the QA\QC process and I understand how busy @A-M-Pearce is with **Lakes of Texas**, **Interns**, **RDC work**, and the **"corrupt" StratMap 2020 CapArea & McLennan Imagery** #49 images.  But can we get USDA APFO to make any changes (re-fly) areas we are concerned about?

Also using the APFO service link would not be my choice.

**Comment by gmullins** [comment]
@mitchellryant I think you're suggesting we cut the Quality Assurance for the CCMs? You are correct in that we cannot ask for reflights of missing data, but I still think it is worth us opening each CCM and giving them a quick peek to ensure correct county coverage and that the files are not corrupt before we make them available on the DataHub. This could reduce the number of questions asked or issues identified later. I think we identified the 2020 CapArea orthos were not reviewed as closely as needed by the assigned PM. Yes, Aaron has a number of duties. He is not the only one checking out the CCMs. 

Thank you for finding the DOQQs on Earth Explorer! @A-M-Pearce Can you please download a few and compare them with some from 2018? File type, number of bands, projection and bit depth would be good to compare. 

If these look ok to move forward with, is there a bulk download option to go straight to where Ryan needs them? 

Thank you both!

**Comment by A-M-Pearce** [comment]
@gmullins @mitchellryant I've opened up QA for the CCMs to the interns, but with the second shipment of the scanning project being sent out on March 15th, everyone is finishing up what they can for that. 3/8ths of the CCMs are fully reviewed, and the rest should be finished end of next week, if not the week after. If this needs to be re-prioritized I'm happy to do that. 

The DOQQs on Earth Explorer look pretty good to me. Comparing it to one from 2018, they look pretty sharp. In regards to the specs: 

- GeoTIF 
- 4 Bands
- NAD83 UTM Zone projections
- 8 Bit Depth

They're also CNIR images, so they come with NC and CIR options. Earth Explorer has a bulk downloader that should be what we need. I haven't found anything about max order sizes, so hopefully it can handle downloading the full collection all in one go.

**Comment by mitchellryant** [comment]
- @gmullins I get it especially with what is going on with StratMap 2020 CapArea & McLennan Imagery #49.
- @gmullins I was wondering if they are on Earth Explorer does the USGS have them somewhere that can be access via other tools.  Claire gave JT a bunch of FTP links to download the USGS 2019 Hurricane Lidar #56. 
S3 Location managed by USGS - https://prd-tnm.s3.amazonaws.com/index.html?prefix=StagedProducts/NAIP/
S3 location managed by ESRI for USDA - s3://naip-source/tx/
FTP location managed by USGS - ftp://rockyftp.cr.usgs.gov
- @A-M-Pearce the USGS bulk downloader it a Java based application, and i have never gotten it to work on a TWDB machine.

**Comment by A-M-Pearce** [comment]
CCM QC has been completed, all counties are looking good!

**Comment by mitchellryant** [comment]
@A-M-Pearce  Here is a refresher on filling out the rest of the console.

open api.tnris.org/admin
collection catalog -> dataset collections -> Search NAIP -> Find the 2020 Texas NAIP (the only one that is not Public)

At this point you only need to fill out the desc. 

If you want you can create new images and upload them. There are some place holders loaded. No sure who sees these, since they are on a different tab. Just load a CCM in Arc, find something "interesting" and take a screen shot or snip. Edit that picture in Photos, and change the aspect ratio to 16:9 widescreen. 

For the desc I would start by saying **`At this time the individual digital ortho quarter quads (DOQQS) are not available.`** then some gibberish about the collection. As you know no one really reads that part.  Maybe from the metadata.

**Comment by A-M-Pearce** [comment]
The DataHub collection has been created and the collection console/imagery upload has been completed. @pwblanton will you please review the description and formatting when you're able?

**Comment by A-M-Pearce** [comment]
@geochik I've written out the tweet for the NAIP 2020 dataset, let me know what you think! I can always rework the text or the picture I put together:

The 2020 NAIP Aerial Imagery is Live on the DataHub! Available as Compressed County Mosaics in both Natural Color and Color Infrared. Download them today!  [https://data.tnris.org/collection/aa5183ca-a1bd-4b5f-9b63-4ba48d01b83d](url)

![image](https://user-images.githubusercontent.com/75264751/113308369-b6556c00-92cb-11eb-8691-e2e0190ac73f.png)

**Comment by gmullins** [comment]
Looks like we won't have DOQQs until June at the earliest. Email from USDA [Geospatial Services Branch](https://www.fsa.usda.gov/programs-and-services/aerial-photography/imagery-products/about-apfo/geospatial-service/index) (formerly APFO):

Hi Gayla,

The TNRIS office is mentioned by many of our customers and a reliable source for TX NAIP imagery. Unfortunately, the 2020 TX NAIP is the last state to be inspected and expected to be released in June. I will place you on our email notification list when the 2020 NAIP becomes available to the public.

Thank you for asking.

David Parry

**Comment by mitchellryant** [comment]
Why do we need 11.8 TB of Tiffs? 

- They will never make to the network. 
- We do not get a great number (if any) of requests for them.
- In fact, they will just be moved from S3 to Glacier and the process for pulling them out of Glacier can be a bit cumbersome and time consuming. 
- any customer requesting tiffs would have to wait an extra week to temporarily change the storage type in AWS and this change cannot be made by RDC.
- Any request could be given to USGS Earth Explorer for download.

**Comment by ThorTheDestroyer** [comment]
If the data is readily available and accessible through a federal entity, I concur on why we would house it. We only have the compressed LAZ format for some of the USGS lidar datasets.

**Comment by mitchellryant** [comment]
As of July 27.
![thumbnail_image004](https://user-images.githubusercontent.com/8459928/127154692-7fec60f3-62dc-49d2-8c6c-ab552620f837.png)

**Comment by mitchellryant** [comment]
**unreadable**
m_2809623_ne_14_060_20201029.jp2
m_2809626_se_14_060_20201029.jp2
m_3210356_ne_13_060_20201001.jp2

m_3210559_sw_13_060_20200523.tif
