### ISSUE TITLE
North & Central Texas Lidar

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/incoming-data#57]
The owner of this issue (person who opened it) is responsible for ensuring each task is completed. 
Please reassign issues when work is complete. The owner of this issue is responsible for checking in with workmates on progress of each task.

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization, data conversion]  @mitchellryant 
- [ ] Creation of derivative products [hypso and metadata] @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**API\data.tnris.org**
- [x] Create API collection @mitchellryant
- [x] Complete API console collection form including metadata and description @ThorTheDestroyer 
- [x] Crop & Upload Images @ThorTheDestroyer
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer<br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_
- [x] Review Description and Formatting @pwblanton https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @mitchellryant 

**data.tnris.org v2**
- [x] Create Single part polygon to show data extent. @ThorTheDestroyer
- No Vertices, holes, or donuts (unless to directly shows in the data)
- Boundary extent needs to be projected to 4326
- Boundary extent shapefile need to be "Generalized" by 10m
- Boundary extent shapefile will be uploaded to API console

**Download\Prod**
- [x] Move data to production shares @mitchellryant
- [x] Update Lidar Selector feature class & downloadable index @mitchellryant
- [x] Make collection public  @mitchellryant 
- [x] Inform TNRIS staff of data availability @mitchellryant
- [ ] Update AGO Map to reflect new collection @ThorTheDestroyer

**Twitter**
- [ ] Draft Tweet content, link, and image in Comment @ThorTheDestroyer
- [ ] Post Tweet @geochik

**Comment by ThorTheDestroyer** [comment]
@pwblanton please review the console description below. 

This StratMap lidar project covers portions of 21 counties in northern and central Texas.  This project was managed by the Texas Strategic Mapping (StratMap) Program and utilized the StratMap contracts held by the Department of Information Resources (DIR). Collection took place January 7th, 2020 through April 24, 2020 with re-flights in June and August 2020. Data was collected and processed by the Sanborn Mapping Company, LLC with third party quality assurance/quality control performed by AECOM.  Eisenhower State Park was collected at a higher point density of 8 points per square meter.  

The StratMap contributing partner for this project was the Texas Parks and Wildlife Department (TPWD) and the City of Marble Falls, Texas. Lidar acquired from this project will be used for floodplain management and planning, feature extraction, water quality modeling, stream restoration potential analysis, change detection, 9-1-1, wildfire mitigation, and habitat identification/modeling for endangered species.

Points are classified based on the following classifications. 

Class 1: Unclassified
Class 2: Ground
Class 3: Low vegetation
Class 4: Medium vegetation
Class 5: Tall vegetation
Class 6: Buildings
Class 7: Low Point (noise)
Class 9: Water
Class 10: Ignored Ground
Class 14: Culverts
Class 17: Bridges

**Comment by rwade2126** [comment]
Joey—

I edited the entry, clicked Save and Continue, and received this message:

Forbidden (403)
CSRF verification failed. Request aborted.
You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.
If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for “same-origin” requests.
More information is available with DEBUG=True.

I don’t know what else to do.

Patricia

**Comment by pwblanton** [comment]
This StratMap lidar project covers portions of 21 counties in northern and central Texas. This project was managed by the Texas Strategic Mapping (StratMap) Program and utilized the StratMap contracts held by the Texas Department of Information Resources (DIR). Collection took place January 7, 2020, through April 24, 2020 with re-flights in June and August 2020. Data was collected and processed by the Sanborn Mapping Company, LLC with third party quality assurance/quality control performed by AECOM. Eisenhower State Park was collected at a higher point density of 8 points per square meter.

The StratMap contributing partner for this project was the Texas Parks and Wildlife Department (TPWD) and the City of Marble Falls, Texas. Lidar acquired from this project will be used for floodplain management and planning, feature extraction, water quality modeling, stream restoration potential analysis, change detection, 9-1-1, wildfire mitigation, and habitat identification/modeling for endangered species.

Points are classified based on the following classifications.

Class 1: Unclassified
Class 2: Ground
Class 3: Low vegetation
Class 4: Medium vegetation
Class 5: Tall vegetation
Class 6: Buildings
Class 7: Low Point (noise)
Class 9: Water
Class 10: Ignored Ground
Class 14: Culverts
Class 17: Bridges

**Comment by mitchellryant** [comment]
@ThorTheDestroyer @geochik @gmullins 

Dataset collection has been public since 2021-05-27.
still wanting\needing to tweet? or can the issues be closed?

**Comment by geochik** [comment]
Ah! This was right at the time I was out. 
@ThorTheDestroyer can you please provide me with an image to go with a Tweet? Some verbiage would really help, too. 
@mitchellryant let's go ahead and close this issue. No need to wait for the Tweet. Thank you!!
