### ISSUE TITLE
2021 CapArea, Brazos & Kerr

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/incoming-data#58]
The owner of this issue (person who opened it) is responsible for ensuring each task is completed. 
Please reassign issues when work is complete. The owner of this issue is responsible for checking in with workmates on progress of each task.

**Data**
- [x] Enter dataset on StratMap Incoming data xlsx sheet @ThorTheDestroyer 
- [x] Route Data Shipment (copy data to TNRIS Projects share) @ThorTheDestroyer 
- [x] Data Processing (renaming file, data organization) @mitchellryant
- [x] Creation of derivative products [compressed images] @ThorTheDestroyer 
- [x] Quality Assurance @ThorTheDestroyer

**API\data.tnris.org**
- [x] Create API collection @mitchellryant
- [x] Complete API console collection form including metadata and description @ThorTheDestroyer
- [x] Crop & Upload Images @ThorTheDestroyer
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer<br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_
- [x] Review Description and Formatting @pwblanton https://api.tnris.org/admin/lcd/collection/
- [x] Add resources @mitchellryant

**data.tnris.org v2** @ThorTheDestroyer 
- [x] Create Single polygon coverage, by merging all polygons together.
	If your area is county based please use the TxDOT Generalized Boundaries.
	Use Editing Merge, not Merge Tool.    
- [x] No Vertices, holes, or donuts (unless to directly shows in the data)
- [x] Projected shape to 4326
- [x] Generalized shape by 10m
- [x] Create 50 Char Text field called "cllct_id"
- [x] Populate field to be Collection ID, you can get this from the API console.
- [x] Convert shape file to JSON using Feature to JSON tool.
- [x] Load JSON into API console.

**Download\Prod**
- [x] Move data to production shares @mitchellryant
- [x] Make collection public @mitchellryant
~~- [ ] WMS Link @mitchellryant~~ 
- [ ] Inform TNRIS staff of data availability @ThorTheDestroyer 

**Twitter**
- [ ] Draft Tweet content, link, and image in Comment @ThorTheDestroyer 
- [ ] Post Tweet @geochik

**Comment by mitchellryant** [comment]
@ThorTheDestroyer there are 240 files (120 jp2 and j2w) with _hr4 at the end of the name. is this expected?

**Comment by mitchellryant** [comment]
I would suggest making a "map" showing the coverage areas of the different resolutions.

**Comment by ThorTheDestroyer** [comment]
hr4 is an unknown. I'll look into it and send you a decision about them. I will generate/upload a coverage map to the console.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer Here are what the hr4 images cover.

![hr4](https://user-images.githubusercontent.com/8459928/122225163-72114b00-ce7a-11eb-917c-d4c0f1a5fa7d.png)

**Comment by ThorTheDestroyer** [comment]
I was unable to track down those tiles in the repositories to confirm this, but those are duplicate tiles delivered for TMPA's in their requested NAD27 projection.  
![image](https://user-images.githubusercontent.com/8398036/122289880-d0f5b500-ceb8-11eb-85de-8207aa36f13e.png)

**Comment by ThorTheDestroyer** [comment]
@pwblanton please review the description.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer tile index?

**Comment by mitchellryant** [comment]
@ThorTheDestroyer @gmullins @pwblanton 

are we ready to publish?

**Comment by mitchellryant** [comment]
@ThorTheDestroyer Data is live https://data.tnris.org/collection/3e1530dc-d5be-4683-811b-9d4b162f0aa9
