### ISSUE TITLE
2021 Address Points Dataset Collection

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/incoming-data#59]
The owner of this issue (person who opened it) is responsible for ensuring each task is completed. 
Please reassign issues when work is complete. The owner of this issue is responsible for checking in with workmates on progress of each task.

**Data**
- [x] Add data to measures spreadsheet @LaurenKirk 
~~- [x] Route Data Shipment [copy data to TNRIS Projects share] @LaurenKirk~~
- [x] Data Processing [renaming file, data organization]  @LaurenKirk
```
naming convention for shape and fgdb.
stratmap19-addresspoints_fipscode_countyname_date.extension
stratmap19-addresspoints_48001_anderson_201904.shp
stratmap19-addresspoints_48001_anderson_201904.gdb
```
- [x] Quality Assurance @LaurenKirk

**API\data.tnris.org**
- [x] Create API collection @mitchellryant
- [x] Complete API console collection form including metadata and description @LaurenKirk 
- [x] Upload supplemental info (breaklines, reports, index) @LaurenKirk

`If zip file is too large (more than 75MB) please let` @mitchellryant `know and the file can be loaded in another way.`
- [x] Crop & Upload Images @LaurenKirk
- [x] Review Description and Formatting @pwblanton https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @mitchellryant 

**data.tnris.org v2**
- [x] Create Single part polygon to show data extent. @LaurenKirk
- No Vertices, holes, or donuts (unless to directly shows in the data)
- Boundary extent needs to be projected to 4326
- Boundary extent shapefile need to be "Generalized" by 10m
- Boundary extent shapefile will be uploaded to API console

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant 
- [x] Inform TNRIS staff of data availability @LaurenKirk
- [x] Update AGO Map to reflect update @LaurenKirk

**Twitter**
- [x] Draft Tweet content, link, and image in Comment @LaurenKirk
- [x] Post Tweet @geochik

**Comment by mitchellryant** [comment]
@LaurenKirk You need to complete the lookup section.

**Comment by LaurenKirk** [comment]
@mitchellryant lookup section complete.

**Comment by LaurenKirk** [comment]
@mitchellryant all boxes checked. gonna close
