### ISSUE TITLE
USGS 2018 Eastern Texas

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/incoming-data#6]
Please reassign issues when your work is complete.

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization]  @ThorTheDestroyer
- [x] Creation of derivative products [hypso and metadata] @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**DataHub**
- [x] Create collection @mitchellryant
- [x] Complete console collection form including metadata and description @ThorTheDestroyer 
- [x] Create Images, place on Website Dir @ThorTheDestroyer 
- [x] Crop & Upload Images @christoball 
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer<br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_
- [x] Review Description @pwblanton
- [x] Add resources  @mitchellryant 

**Download\Prod**
- [x] Move data to production shares @mitchellryant 
- [x] Make collection public  @mitchellryant 
- [x]  Inform TNRIS staff of data availability @mitchellryant 

**News Article**
* If you choose to write an article about the data release
* Create a new issue in the [tnris.org repo](https://github.com/TNRIS/tnris.org). 
* Please assign to yourself and @christoball.
* Use the Data Release and New Article labels.
* Provide all content as a comment in the issue.

**Comment by ThorTheDestroyer** [comment]
@christoball Images are loaded to Website\datacatalog\images\usgs18-eastern

**Comment by christoball** [comment]
@ThorTheDestroyer @mitchellryant Images have been processed and uploaded to the collection on datahub

**Comment by mitchellryant** [comment]
Collection Published 10/21/2019
