### ISSUE TITLE
2021 McLennan Lidar

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/incoming-data#61]
The owner of this issue (person who opened it) is responsible for ensuring each task is completed. 
Please reassign issues when work is complete. The owner of this issue is responsible for checking in with workmates on progress of each task.

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization, data conversion]  @mitchellryant 
- [x] Creation of derivative products [hypso and metadata] @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**API\data.tnris.org**
- [x] Create API collection @mitchellryant
- [x] Complete API console collection form including metadata and description @ThorTheDestroyer 
- [x] Crop & Upload Images @ThorTheDestroyer
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer<br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_
- [x] Review Description and Formatting @pwblanton https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @mitchellryant 

**data.tnris.org v2** @ThorTheDestroyer 
- [x] Create Single polygon coverage, by merging all polygons together.
	If your area is county based please use the TxDOT Generalized Boundaries.
	Use Editing Merge, not Merge Tool.    
- [x] No Vertices, holes, or donuts (unless to directly shows in the data)
- [x] Projected shape to 4326
- [x] Generalized shape by 10m
- [x] Create 50 Char Text field called "cllct_id"
- [x] Populate field to be Collection ID, you can get this from the API console.
- [x] Convert shape file to JSON using Feature to JSON tool.
- [x] Load JSON into API console.

**Download\Prod**
- [x] Move data to production shares @mitchellryant
- [x] Update Lidar Selector feature class & downloadable index @mitchellryant
- [x] Make collection public  @mitchellryant 
- [x] Inform TNRIS staff of data availability @ThorTheDestroyer
- [x] Update AGO Map to reflect new collection @ThorTheDestroyer

**Twitter**
- [x] Draft Tweet content, link, and image in Comment @ThorTheDestroyer
- [x] Post Tweet @geochik

**Comment by mitchellryant** [comment]
@ThorTheDestroyer please check the collection to make sure it is completely filled out.

**Comment by ThorTheDestroyer** [comment]
@mitchellryant Let me know if this one works. 
[mclennan21_lidar_footprint.zip](https://github.com/TNRIS/incoming-data/files/6983173/mclennan21_lidar_footprint.zip)

**Comment by ThorTheDestroyer** [comment]
@geochik twitter coverage image. 
![mclennan_21_coverage](https://user-images.githubusercontent.com/8398036/129379350-a335a37f-a693-440c-a3f4-4862ccc2b40d.png)

**Comment by ThorTheDestroyer** [comment]
@geochik twitter link and proposed tweet text. 

Now available for download! StratMap 2021 lidar covering portions of McLennan County, Texas. 
https://data.tnris.org/collection/7cbe9785-6e63-4428-bd50-56c64cc3b6fc

**Comment by geochik** [comment]
All the boxes are checked so I am taking the liberty to close this issue!
