### ISSUE TITLE
2021 Bois D'Arc

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/incoming-data#62]
The owner of this issue (person who opened it) is responsible for ensuring each task is completed. 
Please reassign issues when work is complete. The owner of this issue is responsible for checking in with workmates on progress of each task.

**Data**
- [ ] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [ ] Data Processing [renaming file, data organization, data conversion]  @mitchellryant 
- [x] Creation of derivative products [hypso and metadata] @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**API\data.tnris.org**
- [x] Create API collection @mitchellryant
- [x] Complete API console collection form including metadata and description @ThorTheDestroyer 
- [x] Crop & Upload Images @ThorTheDestroyer
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer<br/>_**If zip file is too large (more than 75MB) please let @mitchellryant know and the file can be loaded in another way.**_
- [x] Review Description and Formatting @pwblanton https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @mitchellryant 

**data.tnris.org v2** @ThorTheDestroyer 
- [x] Create Single polygon coverage, by mergeing all polygons together.
	If your area is county based please use the TxDOT Generalized Boundaries.
	Use Editing Merge, not Merge Tool.    
- [x] No Vertices, holes, or donuts (unless to directly shows in the data)
- [x] Projected shape to 4326
- [x] Generalized shape by 10m
- [x] Create 50 Char Text field clalled "cllct_id"
- [x] Populate field to be Collection ID, you can get this from the API console.
- [x] Convert shape file to json using Feature to JSON tool. Use Formatted and Geo Options
- [x] Load JSON into API console. https://api.tnris.org/admin/lcd/collectionfootprint/

**Download\Prod**
- [x] Move data to production shares @mitchellryant
~~- [ ] Update Lidar Selector feature class & downloadable index @mitchellryant~~
- [x] Make collection public  @mitchellryant 
- [ ] Inform TNRIS staff of data availability @ThorTheDestroyer
- [ ] Update AGO Map to reflect new collection @ThorTheDestroyer

**Twitter**
- [ ] Draft Tweet content, link, and image in Comment @ThorTheDestroyer
- [ ] Post Tweet @geochik

**Comment by ThorTheDestroyer** [comment]
Creating issue now, but currently awaiting final QAQC report.

**Comment by geochik** [comment]
Tweet complete!
