### ISSUE TITLE
StratMap 2021 28cm|50cm Bexar & Travis Counties Lidar

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/incoming-data#64]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please reassign issues when work is complete. The owner of this issue is responsible for checking in with workmates on progress of each task.***

**Data**
- [x] Add data to measures spreadsheet @ThorTheDestroyer
- [x] Route Data Shipment [copy data to TNRIS Projects share] @ThorTheDestroyer 
- [x] Data Processing [renaming file, data organization, data conversion]  @mitchellryant 
- [ ] Creation of derivative products [hypso and metadata] @ThorTheDestroyer
- [x] Quality Assurance @ThorTheDestroyer

**API\data.tnris.org**
- [x] Create API collection @mitchellryant
- [x] Complete API console collection form including metadata and description @ThorTheDestroyer 
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer

`If zip file is too large (more than 75MB) please let` @mitchellryant `know and the file can be loaded in another way.`
- [x] Crop & Upload Images @ThorTheDestroyer
- [x] Review Description and Formatting @pwblanton https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @mitchellryant 
- [x] Create Single polygon coverage, by merging all polygons together. @ThorTheDestroyer
	1. If your area is county based please use the TxDOT Generalized Boundaries.
	2. Use Editing Merge, not Merge Tool.    
	3. No Vertices, holes, or donuts (unless to directly shows in the data)
	4. Projected shape to 4326
	5. Generalized shape by 10m
	6. Convert shape file to json using Feature to JSON tool. Use Formatted and Geo Options
	7. Load JSON into API console. https://api.tnris.org/admin/lcd/collectionfootprint/

**Download\Prod**
- [x] Move data to production shares @mitchellryant
- [x] Update Lidar Selector feature class & downloadable index @mitchellryant
- [x] Make collection public  @mitchellryant 
- [ ] Inform TNRIS staff of data availability @ThorTheDestroyer
- [ ] Update AGO Map to reflect new collection @ThorTheDestroyer

**Twitter**
- [x] Draft Tweet content, link, and image in Comment @ThorTheDestroyer
- [x] Post Tweet @lebell @space-longoria

**Comment by mitchellryant** [comment]
@ThorTheDestroyer where is it and what is it?

**Comment by ThorTheDestroyer** [comment]
2277, 2278. It is in state plane.

**Comment by ThorTheDestroyer** [comment]
renamed dems have been uploaded to port of lasers

**Comment by mitchellryant** [comment]
@ThorTheDestroyer got an index?

**Comment by ThorTheDestroyer** [comment]
[travis-bexar-tiles-index.zip](https://github.com/TNRIS/incoming-data/files/8572377/travis-bexar-tiles-index.zip)

**Comment by ThorTheDestroyer** [comment]
descriptions reviewed and approved by @gmullins

**Comment by ThorTheDestroyer** [comment]
@mitchellryant can't start a new footprint collection in the api. here is the json for the footprint. 
[travis_bexar_footprint.zip](https://github.com/TNRIS/incoming-data/files/8708951/travis_bexar_footprint.zip)

**Comment by ThorTheDestroyer** [comment]
![Layout](https://user-images.githubusercontent.com/8398036/169120235-a191184a-8eb5-40e1-bcf8-0aa203ece0b2.png)

**Comment by ThorTheDestroyer** [comment]
![image](https://user-images.githubusercontent.com/8398036/169120970-cf8c833b-af3b-4d5d-a71c-ed713120ea38.png)

**Comment by ThorTheDestroyer** [comment]
Twitter Draft: 
Now available for download! StratMap 2021 lidar covering portions of Central Texas including high density 12ppsm coverage for the City of Austin.

**Comment by space-longoria** [comment]
@ThorTheDestroyer how soon can this tweet be published?

**Comment by mitchellryant** [comment]
@space-longoria the [data set collection](https://data.tnris.org/collection?c=447db89a-58ee-4a1b-a61f-b918af2fb0bb#5.12/29.94/-97.47) is currently available on data.tnris.org, so you can tweet at you convenience!
