### ISSUE TITLE
StratMap 2020 North-Central-TX Contours [Data Update]

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/incoming-data#72]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [x] Data Processing [renaming file, data organization] per given naming convention @csidenblad 
- [x] Quality Assurance @csidenblad @ThorTheDestroyer 
- [x] Metadata @csidenblad 

**API\data.tnris.org**
- [x] Upload updated data @mitchellryant
- [x] Add new files to API @mitchellryant 
	
**Download\Prod**
- [x] Move data to production shares @mitchellryant
- [ ] ~~Inform TNRIS staff of data availability ***(if necessary)***~~

**Comment by mitchellryant** [comment]
@csidenblad please see @ThorTheDestroyer for metadata txt template!

**Comment by csidenblad** [comment]
@mitchellryant I created new map catalogs to check for the missing tiles. Only tiles that seemed to be missing were over water features. I figured no data were generated and this is why there were missing tiles.

**Comment by ThorTheDestroyer** [comment]
0-100 missing tiles is normal, but over 300 missing tiles(where full water tiles were already removed in the dems) seems like a lot.  Can you export the bbox coverages for both of the catalogs?

**Comment by csidenblad** [comment]
I've exported them. Shapefiles are located here: 
W:\north-central-tx-contours\QC

**Comment by mitchellryant** [comment]
all that sounds good, but to me like a Tuesday problem.

**Comment by mitchellryant** [comment]
3097011 has 80 5ft, but only 1 2ft and no shp for the 2ft.

![image](https://user-images.githubusercontent.com/8459928/176027990-e0d51cab-d093-41e6-86e0-afa4cfcb0d23.png)

**Comment by ThorTheDestroyer** [comment]
according to the shapes there are 6444 of both 2ft and 5ft.  did some not copy over?

**Comment by mitchellryant** [comment]
they are not in the shps folders now so if they did not move, then they disappeared like Keyser Söze

**Comment by csidenblad** [comment]
I can reexport to shape and see if we can generate the missing tiles

**Comment by mitchellryant** [comment]
seems like only 2ft.

**Comment by csidenblad** [comment]
@mitchellryant you took my shapefiles :(

**Comment by csidenblad** [comment]
Awesome!! Thanks Ryan.
