### ISSUE TITLE
2022 StratMap Address Points Dataset Collection

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/incoming-data#74]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [x] Add data to measures spreadsheet @LaurenKirk 
- [x] Route Data Shipment [copy data to TNRIS Projects share] @LaurenKirk
- [x] Data Processing [renaming file, data organization]  @LaurenKirk
```
naming convention for shape and fgdb.
stratmap19-addresspoints_fipscode_countyname_date.extension
stratmap19-addresspoints_48001_anderson_201904.shp
stratmap19-addresspoints_48001_anderson_201904.gdb

```
- [x] Quality Assurance @LaurenKirk

**API\data.tnris.org**
- [x] Create API collection @mitchellryant
- [x] Complete API console collection form including metadata and description @LaurenKirk 
- [x] Upload supplemental info (breaklines, reports, index) @LaurenKirk

`If zip file is too large (more than 75MB) please let` @mitchellryant `know and the file can be loaded in another way.`
- [x] Crop & Upload Images @LaurenKirk
- [x] Review Description and Formatting @pwblanton https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @csidenblad 
- [x] Create Single polygon coverage, by merging all polygons together. @LaurenKirk
	1. If your area is county based please use the TxDOT Generalized Boundaries.
	2. Use Editing Merge, not Merge Tool.    
	3. No Vertices, holes, or donuts (unless to directly shows in the data)
	4. Projected shape to 4326
	5. Generalized shape by 10m
	6. Convert shape file to json using Feature to JSON tool. Use Formatted and Geo Options
	7. Load JSON into API console. https://api.tnris.org/admin/lcd/collectionfootprint/'
	
**Download\Prod**
- [x] Move data to production shares @csidenblad 
- [x] Make collection public  @csidenblad
- [x] Inform TNRIS staff of data availability @LaurenKirk
- [x] Update AGO Map to reflect update @LaurenKirk

**Twitter**
- [x] Draft Tweet content, link, and image in Comment @LaurenKirk
- [x] Post Tweet @lebell @space-longoria

**Comment by mitchellryant** [comment]
¿Dónde están los datos? @LaurenKirk

**Comment by LaurenKirk** [comment]
@mitchellryant All of the address point data has been copied to Gorgoroth/QAQC. I've also included the footprints (shp & geoJSON) and DataHub images (already uploaded on the API). No Statewide FGDB at this time. I'll continue down that dark road on Monday and will also update the AGO maps.

@pwblanton can you please review information on the API? You'll also want to use FireFox web browser. Info at: https://api.tnris.org/admin/lcd/collection/842bafc7-cabf-483b-b5fb-ab21638b5c72/change/

**Comment by pwblanton** [comment]
I made a few edits and saved.

**Comment by LaurenKirk** [comment]
@pwblanton Thank you Patricia!

**Comment by pwblanton** [comment]
Sorry for the late response… I am definitely not a regular user of GitHub/API.
