### ISSUE TITLE
2022 Rivers, Streams, and Waterbodies Update

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/incoming-data#76]
**Data**
- [x] Download data from source @csidenblad 
- [x] Add data to measures spreadsheet @csidenblad 
- [x] Place data on network or S3 @csidenblad 
- [x] Data Processing [renaming file, data organization] per given naming convention @csidenblad 
- [ ] Quality Assurance @ThorTheDestroyer 

**API\data.tnris.org**
- [x] Upload updated data @mitchellryant
- [x] Update Publication Date ***(if necessary)*** @mitchellryant
	
**Download\Prod**
- [x] Move data to production shares @mitchellryant
- [x] Update Web Service and API collection link(s) ***(if necessary)*** @mitchellryant
~~- [ ] Inform TNRIS staff of data availability ***(if necessary)***~~

**Comment by csidenblad** [comment]
@ThorTheDestroyer Data has been assembled and can be found on gorgoroth/QAQC/StratMap/NHD if you'd like to give it a look over.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer @csidenblad issues have arisen!
