### ISSUE TITLE
usgs-2019-70cm-pecos-dallas contours 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/incoming-data#77]
**Data**
- [ ] Add data to measures spreadsheet
- [x] Data Processing [renaming file, data organization] per given naming convention @csidenblad 
- [x] Quality Assurance @ThorTheDestroyer 

**API\data.tnris.org**
- [x] Upload updated data @mitchellryant @csidenblad
	
**Download\Prod**
- [x] Move data to production shares @mitchellryant @csidenblad 
~~- [ ] Update Web Service and API collection link(s) ***(if necessary)*** @mitchellryant @csidenblad~~

**Comment by ThorTheDestroyer** [comment]
@mitchellryant Contours look great. Ready to publish.
