### ISSUE TITLE
2022 Address Points Statewide

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/incoming-data#78]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [x] Place data on network or S3 **(QAQC\StratMap\AP_LP\2022)**
- [x] Quality Assurance @LaurenKirk 

**API\data.tnris.org**
- [x] Upload updated data @csidenblad 

	
**Download\Prod**
- [x] Move data to production shares @csidenblad 
- [x] Update Web Service and API collection link(s) ***(if necessary)*** @csidenblad

**Comment by LaurenKirk** [comment]
@csidenblad @mitchellryant Address Points look good to go!
