### ISSUE TITLE
2022 CAPCOG 12in NCCIR Imagery

### ISSUE THREAD

**Issue by ThorTheDestroyer** [TNRIS/incoming-data#81]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [x] Enter dataset on StratMap Incoming data xlsx sheet @ThorTheDestroyer 
- [x] Route Data Shipment (copy data to TNRIS Projects share) @ThorTheDestroyer 
- [x] Data Processing (renaming file, data organization) @csidenblad
- [x] Quality Assurance @ThorTheDestroyer

**API\data.tnris.org**
- [x] Create API collection @csidenblad
- [x] Complete API console collection form including metadata and description @ThorTheDestroyer
- [x] Upload supplemental info (breaklines, reports, index) @ThorTheDestroyer

`If zip file is too large (more than 75MB) please let` @csidenblad `know and the file can be loaded in another way.`
- [x] Crop & Upload Images @ThorTheDestroyer
- [x] Review Description and Formatting @pwblanton https://api.tnris.org/admin/lcd/collection/
- [x] Add resources  @csidenblad
- [x] Create Single polygon coverage, by merging all polygons together. @ThorTheDestroyer
	1. If your area is county based please use the TxDOT Generalized Boundaries.
	2. Use Editing Merge, not Merge Tool.    
	3. No Vertices, holes, or donuts (unless to directly shows in the data)
	4. Projected shape to 4326
	5. Generalized shape by 10m
	6. Convert shape file to json using Feature to JSON tool. Use Formatted and Geo Options
	7. Load JSON into API console. https://api.tnris.org/admin/lcd/collectionfootprint/

**Download\Prod**
- [x] Move data to production shares @csidenblad
- [x] Make collection public @csidenblad
- [ ] ~~Web Service Link(s) @csidenblad~~
- [ ] Inform TNRIS staff of data availability @ThorTheDestroyer

**Twitter**
- [ ] Draft Tweet content, link, and image in Comment @ThorTheDestroyer 
- [ ] Post Tweet @lebell @space-longoria

**Comment by ThorTheDestroyer** [comment]
@csidenblad just as an fyi, this is a capcog project, stratmap was not involved.

**Comment by csidenblad** [comment]
@ThorTheDestroyer Thanks for the info Joey. I'll get a collection card up in the API. Will name it 'Capital Area Council of Governments Imagery' and include acquisition year.

**Comment by ThorTheDestroyer** [comment]
@csidenblad  data has finished uploading

**Comment by mitchellryant** [comment]
@ThorTheDestroyer band combo?

**Comment by ThorTheDestroyer** [comment]
@csidenblad can you please create a footprint collection card as well?

**Comment by ThorTheDestroyer** [comment]
@csidenblad @mitchellryant  The index that was on the drive is incorrect. Currently working on obtaining the correct index.

**Comment by ThorTheDestroyer** [comment]
[2022_CAPCOG_Tile-Layout.zip](https://github.com/TNRIS/incoming-data/files/9433026/2022_CAPCOG_Tile-Layout.zip)

**Comment by ThorTheDestroyer** [comment]
@csidenblad can you please create a footprint collection card?  

Also, CAPCOG has requested that we have this data available by September 2nd.  Can you confirm if that will be possible? After Patricia reviews, and I can upload the footprint, everything should be done on my end.

**Comment by mitchellryant** [comment]
it is good that they have goals!

**Comment by ThorTheDestroyer** [comment]
@pwblanton can you please review the api description at your convenience?

**Comment by csidenblad** [comment]
Thanks for the update @ThorTheDestroyer. I'll start zipping it all up today and will reach out as soon as it's up.

**Comment by mitchellryant** [comment]
@ThorTheDestroyer ,

@csidenblad  was out sick today so finished it up for her. should be on the site tomorrow.

**Comment by ThorTheDestroyer** [comment]
Fantastic, much appreciated.
