### ISSUE TITLE
2022 GLO ReGen - State Land Grid Project Phase 1

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/incoming-data#85]
# ***The owner of this issue (person who opened it) is responsible for ensuring each task is completed.***
## ***Please remove any task(s) that do not apply***

**Data**
- [x] Add data to measures spreadsheet @LaurenKirk 
- [x] Route Data Shipment [copy data to TNRIS Projects share] @LaurenKirk
- [x] Data Processing [renaming file, data organization]  @LaurenKirk
- [x] Quality Assurance @LaurenKirk

**API\data.tnris.org**
- [x] Create API collection @csidenblad
- [ ] Complete API console collection form including metadata and description @LaurenKirk 
- [ ] Upload supplemental info (breaklines, reports, index) @LaurenKirk

`If zip file is too large (more than 75MB) please let` @csidenblad `know and the file can be loaded in another way.`
- [ ] Crop & Upload Images @LaurenKirk
- [ ] Review Description and Formatting @pwblanton https://api.tnris.org/admin/lcd/collection/
- [ ] Add resources  @csidenblad 
- [ ] Create Single polygon coverage, by merging all polygons together. @LaurenKirk
	1. If your area is county based please use the TxDOT Generalized Boundaries.
	2. Use Editing Merge, not Merge Tool.    
	3. No Vertices, holes, or donuts (unless to directly shows in the data)
	4. Projected shape to 4326
	5. Generalized shape by 10m
	6. Convert shape file to json using Feature to JSON tool. Use Formatted and Geo Options
	7. Load JSON into API console. https://api.tnris.org/admin/lcd/collectionfootprint/

**Download\Prod**
- [ ] Move data to production shares @csidenblad 
- [ ] Make collection public  @csidenblad 
- [ ] Inform TNRIS staff of data availability @LaurenKirk
- [ ] Update AGO Map to reflect update @LaurenKirk

**Twitter**
- [ ] Draft Tweet content, link, and image in Comment @LaurenKirk
- [ ] Post Tweet @lebell @space-longoria

**Comment by csidenblad** [comment]
Collection has been created in the API 
https://api.tnris.org/admin/lcd/collection/712c0db9-b756-4d5e-9213-03b4021454d9/change/

**Comment by mitchellryant** [comment]
@LaurenKirk we will need name the sums it up the collection name. 

We try to avoid misc punctuation and confusing words and abbreviations  "ReGen".
We also "try" to avoid agency names and abbreviations in collection names.

workshop something with your fellow SM'er or maybe the new marketing specialist.

![image](https://user-images.githubusercontent.com/8459928/195400835-d3c2e31d-29cd-46fc-87bf-a9ab6ec9c183.png)
